[connections.sql]
dialect = "mssql+pyodbc"
host = "PAOLA-LENOVO\\SQLEXPRESS02"
database = "Gestionale"
username = ""
password = ""
# Non inserire la riga 'driver' qui sopra, usa solo la sezione query
query = {"driver" = "SQL Server", "Trusted_Connection" = "yes"}